name: Compile

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup SourcePawn Compiler
      id: setup
      uses: rumblefrog/setup-sp@v1.1.0
      with:
        version: "1.10.x"

    - name: Create plugins directory
      run: mkdir addons/sourcemod/plugins

    - name: Compile plugins
      run: |
        cd addons/sourcemod/scripting
        sed -i -E 's/^(#define\sMHUD_VERSION\s)"(.*)"$/\1"git-${{ github.sha }}"/' include/movementhud.inc
        for file in *.sp; do spcomp $file -i "include" -o "../plugins/${file%.*}.smx"; done;

    - name: Prepare artifact
      run : |
        mkdir artifact
        mv addons artifact

    - name: Upload compiled plugin
      uses: actions/upload-artifact@v3
      with:
        name: movementhud-git-${{ github.sha }}.zip
        path: artifact
